### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by gloatoriginal** [SkyrimTogether/issues-server#12]
## Description
received this error message and server crashed 

```
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [-1586877680]  0: 0x7f00a179ec72: GameServer::Announce()::{lambda()#1}::operator()() const()+0xea2
  [-1586877680]  1: 0x7f00a179f1c9: <unknown>
  [-1586877680]  2: 0x7f00a17a0579: std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)()+0x29
  [-1586877680]  3: 0x7f00a1ba8d4e: __pthread_once_full()+0x52
  [-1586877680]  4: 0x7f00a3dd2508: <unknown>

Backtrace: 0x7f00a179ec72 0x7f00a179f1c9 0x7f00a17a0579 0x7f00a1ba8d4e 0x7f00a3dd2508

```

this was on debian version 9.9
using Docker version 19.03.1, build 74b1e89
```docker run -p 10578:10578/udp tiltedphoques/st-game-server```

## Steps to reproduce

How to reproduce this issue:
not sure, I was asleep.. I know the container had been open for >24hours
1. Start the launcher.
2. Connect login.
3. Fail to login.

## Reproduction rate

How many times can you reproduce it?
0
## Expected result

Describe your expected result.
consistently up
## Your environment
this was on debian version 9.9
using Docker version 19.03.1, build 74b1e89
```docker run -p 10578:10578/udp tiltedphoques/st-game-server```

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
this was on debian version 9.9
using Docker version 19.03.1, build 74b1e89
```docker run -p 10578:10578/udp tiltedphoques/st-game-server```

## Evidence (optional)

Show us what happen.

**Comment by zxyxz** [comment]
I have the same problem
run docker:
`docker run -p 10578:10578/udp tiltedphoques/st-game-server`
error info:
{"date":"2019-09-05 14:12:41,131", "level":"INFO", "event":"register_player_weather", "form_id":298004, "connection_id":1559260475 }
Caught signal 11 (Segmentation fault) in program  [1]
   thread frame     IP       function
  [-734008560]  0: 0x7fc5d44fac02: GameServer::Announce()::{lambda()#1}::operator()() const()+0xea2
  [-734008560]  1: 0x7fc5d44fb159: <unknown>
  [-734008560]  2: 0x7fc5d44fc509: std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)()+0x29
  [-734008560]  3: 0x7fc5d4904d2e: __pthread_once_full()+0x52
  [-734008560]  4: 0x7fc5e2739a28: <unknown>
Backtrace: 0x7fc5d44fac02 0x7fc5d44fb159 0x7fc5d44fc509 0x7fc5d4904d2e 0x7fc5e2739a28

**Comment by yamashi** [comment]
I pushed a potential fix for this just now, the server software should be updated in a few minutes, let me know if this still occurs after using the next patch.

**Comment by zxyxz** [comment]
Thank you very much. I'm testing now.

**Comment by gloatoriginal** [comment]
will test tonight at work atm, just redownload the docker image?

**Comment by zxyxz** [comment]
The problem has changed.
error info :
`Caught signal 11 (Segmentation fault) in program  [1]
   thread frame     IP       function
  [1712044816]  0: 0x7f17661b7382: GameServer::Announce()::{lambda()#1}::operator()() const()+0xea2
  [1712044816]  1: 0x7f17665699ee: execute_native_thread_routine()+0xc
  [1712044816]  2: 0x7f17665c1055: start()+0x3f
Backtrace: 0x7f17661b7382 0x7f17665699ee 0x7f17665c1055
`

**Comment by zxyxz** [comment]
New problems have been discovered.Two players cannot enter a room at the same time.

**Comment by yamashi** [comment]
Alright I pushed another patch, should be available in a few minutes, hopefully this will do the trick.

**Comment by zxyxz** [comment]
Thank you very much！Hope to solve the problem！

**Comment by zxyxz** [comment]
oh my god 
The problem still exists, and there are no error logs

**Comment by zxyxz** [comment]
I tried to use the old image, but I was not allowed to connect.Old image perform better than new ones ！

**Comment by yamashi** [comment]
This is another bug report, that won't be processed here.
